### ISSUE TITLE
Accept markdownlint config file

### ISSUE THREAD

**Issue by XhmikosR** [sagiegurari/grunt-markdownlint#1]
#### Problem Description

Doesn't accept markdownlint config file.

#### Code Example

````js
markdownlint: {
    all: {
        options: {
            config: './markdownlint.json'
        },
        src: [
            'src/**/*.md'
        ]
    }
},
````

I believe this would make things much simpler.

**Comment by XhmikosR** [comment]
Nevermind, I figured it out. It's just the same as markdownlint, `require('foo.json')`

**Comment by sagiegurari** [comment]
I use config: grunt.file.readJSON(rulesFile)
for example:
https://github.com/sagiegurari/js-project-commons/blob/master/lib/grunt/task/markdownlint.js

**Comment by XhmikosR** [comment]
Yeah, I figured so a couple of minutes later :) It's just that it's unusual for grunt plugins, that is all.
