### ISSUE TITLE
Update to use markdownlint 0.4.0

### ISSUE THREAD

**Issue by DavidAnson** [sagiegurari/grunt-markdownlint#3]
> 0.4.0 - Add MD044, enhance MD013/MD032/MD041/MD042/MD043, fix for MD038, dependencies.

**Comment by sagiegurari** [comment]
You are right but I dont have access to a computer right now so will take care in few days

**Comment by DavidAnson** [comment]
No rush! Just leaving a TODO. Thanks for creating and maintaining this project!

**Comment by sagiegurari** [comment]
done
