### ISSUE TITLE
English

### ISSUE THREAD

**Issue by plroebuck** [sagiegurari/grunt-markdownlint#4]
[CONTRIBUTING.md](https://github.com/sagiegurari/grunt-markdownlint/blob/master/.github/CONTRIBUTING.md):
1. First place to go is the repository issues section[,] and I'll try to help as much as possible.
1. This repository is integrated with travis.ci for [continuous] integration.<br>
1. Any fix/enhancement must come with a set of tests to ensure [it's] working well.

**Comment by sagiegurari** [comment]
Thanks :) I'll update the text

**Comment by sagiegurari** [comment]
doc updated. thanks
