### ISSUE TITLE
Provide alternative means (or document) use with `.markdownlint.json`

### ISSUE THREAD

**Issue by plroebuck** [sagiegurari/grunt-markdownlint#5]
#### Problem Description
Grunt task ignores `.markdownlint.json` and only processes rules placed within its `options.config`.
A "markdownlint-cli" user with an existing configuration file (or someone wishing to store tool configuration externally) is SOL. Propose adding `options.configFile` to simplify external configuration; it would read the file's contents and store within `options.config`.

##### Proposed `Gruntfile.coffee` modification (partial)
````coffeescript
  grunt.initConfig
    readme: 'README.md'
    markdownlint:
      options:
        configFile: '.markdownlint.json'
      default:
        src: [
          '<%= readme %>'
        ]
````

Alternatively (or meanwhile), document use of external file configuration.

##### `Gruntfile.coffee` using existing codebase without modification (partial)

````coffeescript
  grunt.initConfig
    readme: 'README.md'
    markdownlint:
      options:
        config: require './.markdownlint.json'
      default:
        src: [
          '<%= readme %>'
        ]
````

**Comment by sagiegurari** [comment]
Can you look at #1 ?
Its really simple to provide a file and actually I use an external file.
But as options you can fo either coded rules or file which is simpler (that's my opinion anyway)

**Comment by plroebuck** [comment]
So I believe my issue stands, backed up by #1. If you don't want to add `configFile`, fine -- add the second code-fence to the `README.md` and we'll call it a day. :)

**Comment by sagiegurari** [comment]
Fair enough. Will add it tomorrow.

**Comment by sagiegurari** [comment]
docs updated with both examples. thanks
