### ISSUE TITLE
Add "engines" specification to "package.json"

### ISSUE THREAD

**Issue by plroebuck** [sagiegurari/grunt-markdownlint#6]
#### Problem Description

This package does not indicate which versions of Node are supported.
For example, your update of "markdownlint" caused the supported version
of Node to change in a patch release. This requires others to have to track
through your commits as well as those of your dependencies to figure out
WTH happened. While I see no reason for this package to have specified a
newer version of "markdownlint" (since its API did not  change), this change
would have been caught by TravisCI if "engines" had been specified.

This fix should **officially** update the package version to **2.0.0**, as should
have occurred for **1.1.5**.

#### Fix to specify Node-6 LTS
```javascript
...
"engines": {
    "node": ">= 6.14.12",
    "npm": ">= 3.10.10"
  }
}
```

**Comment by sagiegurari** [comment]
done
